### ISSUE TITLE
Fill the blank cells in heart_nb notebook.

### ISSUE THREAD

**Issue by agnisain123** [DSCKGEC/heart-saver#11]
The blank cells in the notebook needs to be filled for complete analysis of models to be used in the app. This includes:
- Create a distribution plot with 'Serum Cholesterol in mg/dl' in it's x-axis.
- Create a heatmap of the dataset.
- Find out the ROC curves of all the models used in the dataset.
- Create a barplot which will show the accuracy of different models used as evaluation.

**Comment by debjitpal5040** [comment]
I want to work in this issue, please assign this to me

**Comment by agnisain123** [comment]
Sure! Go ahead. Issue assigned to @debjitpal5040

**Comment by debjitpal5040** [comment]
@agnisain123 I think now you should close this issue.
