### ISSUE TITLE
Add CSS styles to the HTML pages.

### ISSUE THREAD

**Issue by agnisain123** [DSCKGEC/heart-saver#12]
- Add CSS styles to the HTML pages

**Comment by himanshu007-creator** [comment]
HI, i would like to work on this issue

**Comment by agnisain123** [comment]
You have to wait for a while for contributing.

**Comment by ashuydv** [comment]
Hey, I would like to work on this issues

**Comment by Gauravmitra-hash** [comment]
I would like to work on this issue as well. Could we team up and work on this issue?

**Comment by agnisain123** [comment]
@ashuydv @Gauravmitra-hash  I'm very sorry, you cannot contribute to this project as you are **not part of KSoC**. <br/>
**KSoC** is a open-source contest organised by DSC-KGEC. Only the ones who have registered themselves for the contest can contribute to the projects.

**Comment by himanshu007-creator** [comment]
> @ashuydv @Gauravmitra-hash I'm very sorry, you cannot contribute to this project as you are **not part of KSoC**.
> 
> **KSoC** is a open-source contest organised by DSC-KGEC. Only the ones who have registered themselves for the contest can contribute to the projects.

Please share registration link for them here

**Comment by Gauravmitra-hash** [comment]
I actually have registered for the KSoC open-source event . This is why I wanted to work on this issue.

**Comment by himanshu007-creator** [comment]
> I actually have registered for the KSoC open-source event . This is why I wanted to work on this issue.

I don't remember if I have registered or not. Is there a way to check?🙂

**Comment by agnisain123** [comment]
> 
> 
> I actually have registered for the KSoC open-source event . This is why I wanted to work on this issue.

Okay then, go ahead with your contribution. Make sure you respond on our discord server too.

**Comment by agnisain123** [comment]
> 
> 
> > I actually have registered for the KSoC open-source event . This is why I wanted to work on this issue.
> 
> I don't remember if I have registered or not. Is there a way to check?🙂

Do search your mails, if there is any mail from DSC-KGEC regarding KSoC registration OR you have got any invitation to join our discord server.

**Comment by himanshu007-creator** [comment]
> > > I actually have registered for the KSoC open-source event . This is why I wanted to work on this issue.
> > 
> > 
> > I don't remember if I have registered or not. Is there a way to check?🙂
> 
> Do search your mails, if there is any mail from DSC-KGEC regarding KSoC registration OR you have got any invitation to join our discord server.

No, I haven't registered, is it possible to register now?

**Comment by agnisain123** [comment]
> 
> 
> > > > I actually have registered for the KSoC open-source event . This is why I wanted to work on this issue.
> > > 
> > > 
> > > I don't remember if I have registered or not. Is there a way to check?🙂
> > 
> > 
> > Do search your mails, if there is any mail from DSC-KGEC regarding KSoC registration OR you have got any invitation to join our discord server.
> 
> No, I haven't registered, is it possible to register now?

I'm sorry, the registrations have been closed. Make sure you don't forget to join the KSoC next year.
Also, if you really want to contribute in this project, you have to wait till 30th June 2021, that's the last date of the contest.

**Comment by agnisain123** [comment]
Issue solved!
