### ISSUE TITLE
Gradient Boosting Classifier Optimisation

### ISSUE THREAD

**Issue by agnisain123** [DSCKGEC/heart-saver#13]
- Add more arguments to the GradientBoostingClassifier model to increase its accuracy.
- Use the notebook and add the arguments in the Gradient Boosting Classfication cell.
- Print its accuracy and confusion matrix.
- Pickle the file and use it for app.py.

**Comment by debjitpal5040** [comment]
Assign me this please, I want to work in this issue.

**Comment by agnisain123** [comment]
Sure! GO ahead.
Issue #13 assigned to @debjitpal5040
