### ISSUE TITLE
Missing values from the user.

### ISSUE THREAD

**Issue by agnisain123** [DSCKGEC/heart-saver#14]
- Provide a solution to deal with the missing values provided by the user on the web app.

**Comment by debjitpal5040** [comment]
@agnisain123  I have a doubt regarding this issue. Do you want to make the text input fields "required" so that the user must have to provide a value otherwise the form will not be submitted?

**Comment by agnisain123** [comment]
No. You will be working on taking a value which will fill the empty data that was required. Like a mean/mode value.
